<?php
$z[0]=Array("arcurl","",14,29);
$z[1]=Array("title","",38,52);
$z[2]=Array("litpic","",64,79);
$z[3]=Array("title","",87,101);
$z[4]=Array("title","",110,124);
$z[5]=Array("arcurl","",154,169);
$z[6]=Array("title","",178,192);
$z[7]=Array("title","",194,208);
$z[8]=Array("arcurl","",239,254);
$z[9]=Array("title","",263,277);
$z[10]=Array("description","",279,329);
$z[10][4]['function']="cn_substr(@me,140)";

?>