<tr>
                    <td align=left width="310" height="24" class="ask"><a class=b2 href="[field:arcurl/]" title="[field:title/]" class="tag_title_link">[field:title/]</a></td>
                  </tr>
                  <tr>
                    <td align=left width="310" height="24" class="answer"><a class=b2 href="[field:arcurl/]" title="[field:title/]" class="tag_title_link">[field:description function="cn_substr(@me,80)"/]......</a></td>
                  </tr>