<li>
          <div class="img"><a href="[field:arcurl/]" title="[field:title/]"><img src="[field:litpic/]" /></a></div>
          <div class="txt">
            <h2><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h2>
            <p>[field:description function="cn_substr(@me,240)"/]......<a href="[field:arcurl/]" style="color:#ff6600;text-decoration:none;">【点击详情】</a></p>
          </div>
        </li>
        <div class="s"></div>