<li class="mainlevel" id="mainlevel_0[field:global.autoindex/]"><a href="{dede:field name='typeurl'/}"  title="{dede:field name='typename'/}" class="navList">{dede:field name='typename'/}</a>
        <ul id="sub_01" class="menual">
          {dede:channel type='son' noself='yes'}
          <li><a href="[field:typeurl/]">[field:typename/]</a></li>
          {/dede:channel}
        </ul>
      </li>