<a href="[field:arcurl/]" title="[field:title/]"><img src="[field:litpic/]"  alt="[field:title/]" title="[field:title/]"/></a>
        <div class="fNewsTetx">
          <h3><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h3>
          <p>[field:description function="cn_substr(@me,240)"/]...</p>
          <a href="[field:arcurl/]" title="[field:title/]" class="NewsMore">查看详情>></a> </div>