<?php
$z[0]=Array("arcurl","",9,24);
$z[1]=Array("title","",33,47);
$z[2]=Array("litpic","",59,74);
$z[3]=Array("title","",82,96);
$z[4]=Array("title","",105,119);
$z[5]=Array("arcurl","",184,199);
$z[6]=Array("title","",208,222);
$z[7]=Array("title","",224,238);
$z[8]=Array("description","",262,312);
$z[8][4]['function']="cn_substr(@me,240)";
$z[9]=Array("arcurl","",340,355);
$z[10]=Array("title","",364,378);

?>