<li>
            <div class="i_list_pic"><a href="view.php?aid=[field:id/]" title="[field:title/]"><img src="[field:picname/]" alt="[field:title/]"></a></div>
            <div class="i_list_text"><a href="view.php?aid=[field:id/]" title="[field:title/]">
              <h2 style="font-weight:bold;color:#ff0000">[field:title/]</h2>
              <strong>2[field:pubdate function="MyDate('Y.m.d',@me)"/]</strong><span>[field:description function="cn_substr(@me,60)"/]...</span></a></div>
            <div class="c"></div>
          </li>