<?php
$z[0]=Array("global","",56,84);
$z[0][4]['name']="cfg_indexurl";
$z[1]=Array("flink","[field:link /]",137,211);
$z[1][4]['titlelen']="20";
$z[1][4]['row']="10";
$z[1][4]['type']="text";
$z[2]=Array("channel"," <a href=\"[field:typeurl/]\">[field:typename/]</a>|",276,366);
$z[2][4]['type']="top";
$z[3]=Array("global","",408,434);
$z[3][4]['name']="cfg_powerby";
$z[4]=Array("global","",452,476);
$z[4][4]['name']="cfg_beian";
$z[5]=Array("global","",814,842);
$z[5][4]['name']="cfg_indexurl";

?>