<?php
$z[0]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",503,585);
$z[0][4]['typeid']="19";
$z[1]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",599,681);
$z[1][4]['typeid']="25";
$z[2]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",695,777);
$z[2][4]['typeid']="31";
$z[3]=Array("channelartlist","\r\n      <li class=\"mainlevel\" id=\"mainlevel_0[field:global.autoindex/]\"><a href=\"{dede:field name='typeurl'/}\"  title=\"{dede:field name='typename'/}\" class=\"navList\">{dede:field name='typename'/}</a>\r\n        <ul id=\"sub_01\" class=\"menual\">\r\n          {dede:channel type='son' noself='yes'}\r\n          <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n          {/dede:channel}\r\n        </ul>\r\n      </li>\r\n      ",1112,1590);
$z[3][4]['typeid']="top";
$z[4]=Array("arclist","\r\n      <li style=\"background:url([field:litpic/]) no-repeat center 0\"></li>\r\n      ",1684,1813);
$z[4][4]['row']="3";
$z[4][4]['typeid']="32";

?>