<?php
$z[0]=Array("global","",403,431);
$z[0][4]['name']="cfg_indexurl";
$z[1]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",531,613);
$z[1][4]['typeid']="19";
$z[2]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",627,709);
$z[2][4]['typeid']="25";
$z[3]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",723,805);
$z[3][4]['typeid']="31";
$z[4]=Array("global","",1070,1095);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("channelartlist","\r\n      <li class=\"mainlevel\" id=\"mainlevel_0[field:global.autoindex/]\"><a href=\"{dede:field name='typeurl'/}\"  title=\"{dede:field name='typename'/}\" class=\"navList\">{dede:field name='typename'/}</a>\r\n        <ul id=\"sub_01\" class=\"menual\">\r\n          {dede:channel type='son' noself='yes'}\r\n          <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n          {/dede:channel}\r\n        </ul>\r\n      </li>\r\n      ",1165,1643);
$z[5][4]['typeid']="top";
$z[6]=Array("arclist","\r\n      <li style=\"background:url([field:litpic/]) no-repeat center 0\"></li>\r\n      ",1737,1866);
$z[6][4]['row']="3";
$z[6][4]['typeid']="32";

?>