<?php
$z[0]=Array("field","",207,226);
$z[0][4]['name']="title";
$z[1]=Array("global","",227,253);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",294,316);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",356,407);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1145,1181);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",1203,1238);
$z[5][4]['filename']="left.htm";
$z[6]=Array("field","",1308,1330);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n        <dd>\r\n          <div class=\"img\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" /></a></div>\r\n          <div class=\"txt\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></div>\r\n        </dd>\r\n        ",1387,1703);
$z[7][4]['pagesize']="12";
$z[8]=Array("pagelist","",1791,1857);
$z[8][4]['listsize']="5";
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[9]=Array("include","",1910,1947);
$z[9][4]['filename']="footer.htm";

?>