<?php
$z[0]=Array("field","",219,238);
$z[0][4]['name']="title";
$z[1]=Array("global","",239,265);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",309,339);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",376,403);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("include","",1158,1197);
$z[4][4]['filename']="header_m.htm";
$z[5]=Array("field","",1494,1523);
$z[5][4]['name']="typename";
$z[6]=Array("channel","\r\n        <li><a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> <span class=\"commonfont class-down\"></span></li>\r\n        ",1748,2076);
$z[6][4]['type']="son";
$z[6][4]['row']="10";
$z[6][4]['currentstyle']="<li class='hover'><a href='list.php?tid=~id~' ~rel~><span>~typename~</span></a> </li>";
$z[7]=Array("list","\r\n      <li class=\"loop news4\"><a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\"><img  src=\"[field:picname/]\" alt=\"[field:title/]\"><span>[field:title/]</span></a></li>\r\n      ",2254,2474);
$z[7][4]['pagesize']="6";
$z[8]=Array("pagelist","",2511,2577);
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",2631,2670);
$z[9][4]['filename']="footer_m.htm";

?>