<?php
$z[0]=Array("field","",207,226);
$z[0][4]['name']="title";
$z[1]=Array("global","",227,253);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",294,316);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",356,407);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1145,1181);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",1203,1238);
$z[5][4]['filename']="left.htm";
$z[6]=Array("field","",1308,1330);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n        <li>\r\n          <div class=\"img\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" /></a></div>\r\n          <div class=\"txt\">\r\n            <h2><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></h2>\r\n            <p>[field:description function=\"cn_substr(@me,240)\"/]......<a href=\"[field:arcurl/]\" style=\"color:#ff6600;text-decoration:none;\">【点击详情】</a></p>\r\n          </div>\r\n        </li>\r\n        <div class=\"s\"></div>\r\n        ",1402,1929);
$z[7][4]['pagesize']="6";
$z[8]=Array("pagelist","",2017,2083);
$z[8][4]['listsize']="5";
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[9]=Array("include","",2136,2173);
$z[9][4]['filename']="footer.htm";

?>